name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          cache-key: build
          save-cache: ${{ github.ref_name == 'main' }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  cargo-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          restore-cache: false
          components: rustfmt
      - name: Check Formatting
        run: cargo fmt --all -- --check

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          cache-key: clippy
          save-cache: ${{ github.ref_name == 'main' }}
          components: clippy
      - name: Check Clippy Linter
        run: cargo clippy --all-features --all-targets -- -D warnings
